feat: add transaction contextmanager
outcome-co/utils-py pull request #132
Opened 2020-11-30 16:06 UTC by floredelasteyrie

2020-11-30 16:07 UTC, floredelasteyrie commented on src/outcome/utils/transactions.py
> +from transaction import Transaction, TransactionManager
@d-tw do we have to do something special as the import will be optional?

2020-12-01 08:48 UTC, d-tw requested changes

2020-12-01 08:48 UTC, d-tw commented on make/setup.Makefile
> +	poetry install --no-dev --no-interaction --no-ansi --extras all
It's better to put the mark the dependencies as development dependencies

2020-12-01 08:48 UTC, d-tw commented on pyproject.toml
> +all = ["transaction"]
```suggestion
transaction = ["transaction"]
```

2020-12-01 08:48 UTC, d-tw commented on src/outcome/utils/transactions.py
> +    op.apply()
Maybe when auto apply is set to false, the context manager should check if all of the operations were applied, and raise an exception if some operations were skipped

2020-12-01 08:48 UTC, d-tw commented on src/outcome/utils/transactions.py
> +from transaction import Transaction, TransactionManager
You can always make it a bit more dev-friendly:

```suggestion
try:
    from transaction import Transaction, TransactionManager
except ImportError as ex:
    raise Exception('You need to install the 'transaction' extra to use the transaction features') 
```

2020-12-01 08:48 UTC, d-tw commented on src/outcome/utils/transactions.py
> +    ...
This can just be one Exception

2020-12-01 15:31 UTC, d-tw requested changes

2020-12-01 15:31 UTC, d-tw commented on src/outcome/utils/transactions.py
> +    def check_applied(self):
```suggestion
    def ensure_applied(self):
```

2020-12-01 15:31 UTC, d-tw commented on src/outcome/utils/transactions.py
> +    def abort(self, txn):
```suggestion
    def abort(self, txn: Transaction):
```

2020-12-01 15:31 UTC, d-tw commented on src/outcome/utils/transactions.py
> +def transaction(auto_apply=True):
```suggestion
def transaction(auto_apply: bool =True):
```

2020-12-01 16:49 UTC, d-tw approved these changes

2020-12-01 16:58 UTC, merged