feat: semver compatibility check
outcome-co/utils-py pull request #54
Opened 2020-10-02 19:25 UTC by floredelasteyrie

2020-10-02 19:32 UTC, d-tw requested changes

2020-10-02 19:32 UTC, d-tw commented on src/outcome/utils/semver.py
> +    return Compatibility.equal
Do we actually need `equal`? I'm not sure that's a state of compatibility

We'd end up with code like 

```py
compat = compatible(a,b)

if a !== Compatibility.incompatible:
    ...
```

2020-10-02 19:32 UTC, d-tw commented on src/outcome/utils/semver.py
> +        return Compatibility.compatible
How about a unit test? :)

2020-10-02 19:40 UTC, floredelasteyrie commented on src/outcome/utils/semver.py
> +    return Compatibility.equal
I need to know if they're `compatible` and not `equal`, but I don't actually need the `equal` case.
What would I return in that case ?

2020-10-02 19:48 UTC, d-tw commented on src/outcome/utils/semver.py
> +    return Compatibility.equal
I consider it to be two separate pieces of logic.

I would change your `utils` code to be:

```py

class Compatibility(Enum):
    compatible = 'compatible'
    incompatible = 'incompatible'

    # A third case, for potential future use 
    # if we decide to check build or pre-release info
    unknown = 'unknown'


def compatibility(a: str, b: str) -> Compatibility:
    a_parsed = semver.VersionInfo.parse(a)
    b_parsed = semver.VersionInfo.parse(b)

    if a_parsed.major != b_parsed.major:
        return Compatibility.incompatible

    return Compatibility.compatible


def are_compatible(a: str, b: str) -> bool:
    return compatibility(a, b) == Compatibility.compatible
```

Then in your other code, have the following:

```py
if a != b and are_compatible(a, b):
    ...
```

2020-10-02 20:38 UTC, d-tw approved these changes

2020-10-05 10:28 UTC, d-tw approved these changes

2020-10-05 10:28 UTC, merged