feat: persisted cache
outcome-co/utils-py pull request #77
Opened 2020-10-15 10:16 UTC by floredelasteyrie

2020-10-15 10:34 UTC, d-tw requested changes

2020-10-15 10:34 UTC, d-tw commented on src/outcome/utils/cache.py
> +_persisted_cache_path = f'{Path.home()}/.cache/otc-admin/cache.pkl'
`otc-admin`, hardcoded in `utils-py`?

2020-10-15 10:34 UTC, d-tw commented on src/outcome/utils/cache.py
> +    'persisted': {'maxsize': _default_cache_size, 'ttl': _default_cache_ttl, 'path': _persisted_cache_path},
Since the default value is not null, it will attempt to persist by default - I'd recommend setting the default value to `None`

2020-10-15 10:34 UTC, d-tw commented on src/outcome/utils/cache.py
> +            Path(self.persisted_cache_path).parent.mkdir(parents=True, exist_ok=True)
The `mkdir` should be in the `__init__`

2020-10-15 10:34 UTC, d-tw commented on src/outcome/utils/cache.py
> +    _persisted_cache_backend: _persisted_cache_backend,
Do we need a different backend, if persistence is just a setting on the existing backend?

2020-10-15 10:34 UTC, d-tw commented on src/outcome/utils/cache.py
> +                    self.cache = pickle.load(f)  # noqa: S301
What if the values in `arguments` have changed since the cache was pickled?

2020-10-15 10:34 UTC, d-tw commented on test/test_cache.py
> +class TestTTLBackend:
Do we actually do test where we pickle the cache? How do the timers manage? Do the keys expire?

2020-10-15 11:48 UTC, floredelasteyrie commented on src/outcome/utils/cache.py
> +                    self.cache = pickle.load(f)  # noqa: S301
I'm not sure of how we want to check this ?

2020-10-15 11:55 UTC, d-tw commented on src/outcome/utils/cache.py
> +                    self.cache = pickle.load(f)  # noqa: S301
I'd say we need to update the unpickled cache with the new arguments

2020-10-15 12:10 UTC, floredelasteyrie commented on src/outcome/utils/cache.py
> +                    self.cache = pickle.load(f)  # noqa: S301
I can't manage to set these attributes once the TTLCache exists - I get `AttributeError: can't set attribute`, I guess because they're TTLCache properties ?

2020-10-15 13:05 UTC, floredelasteyrie commented on src/outcome/utils/cache.py
> +                    self.cache = pickle.load(f)  # noqa: S301
```suggestion
          _cache = TTLCache(**arguments)
          ...
                with open(self.persisted_cache_path, 'rb') as f:
                    self.cache = pickle.load(f)  # noqa: S301
                    for arg_key in arguments.keys():
                        if getattr(self.cache, arg_key) != getattr(_cache, arg_key):
                            self.cache = _cache
                            break
```

I could try something like that ?

2020-10-16 12:46 UTC, d-tw approved these changes

2020-10-16 12:47 UTC, merged