fix: in memory cache for coroutines
outcome-co/utils-py pull request #95
Opened 2020-10-26 14:22 UTC by floredelasteyrie

2020-10-27 12:42 UTC, d-tw requested changes

2020-10-27 12:42 UTC, d-tw commented on test/test_cache.py
> +        awaited = await co_cache
Maybe assert that we have the same co_cache object

2020-10-27 12:42 UTC, d-tw commented on test/test_cache.py
>          self.time += value + 1
We need to test the persistence in isolation maybe using `pyfakefs`?

We also need to test the co-routine caching - I don't think we have a test for that yet

2020-10-29 18:56 UTC, d-tw approved these changes

2020-10-29 18:56 UTC, d-tw commented on make/ci.Makefile
> +	poetry run coverage run --context=$(COVERAGE_CONTEXT) -m pytest -vv -s --maxfail=1 --ff ./test
```suggestion
	poetry run coverage run --context=$(COVERAGE_CONTEXT) -m pytest -vv --maxfail=1 --ff ./test
```

2020-10-29 18:56 UTC, d-tw commented on src/outcome/utils/cache.py
> +        if self.cache.pop(key, None) is not None and self.persisted_cache_path:
```suggestion
        
        sentinel = object()
        if self.cache.pop(key, sentinel) is not sentinel and self.persisted_cache_path:
```

2020-11-02 16:51 UTC, floredelasteyrie commented on src/outcome/utils/cache.py
> +        if self.cache.pop(key, None) is not None and self.persisted_cache_path:
Is it to make the difference is a `None` value in `cache` ?

2020-11-02 17:39 UTC, d-tw commented on src/outcome/utils/cache.py
> +        if self.cache.pop(key, None) is not None and self.persisted_cache_path:
Yep, creating an instance of `object`, then checking its identity with `is not` ensures that we can distinguish an absent value from any other value

2020-11-02 18:14 UTC, merged